### ISSUE TITLE
Chromancer Example Fails to Build: Missing `math_macros.h` Header

### ISSUE THREAD

**Issue by Abbelsin** [zackees/fastled-wasm#2]
First, I want to say that this app is fantastic and exactly what I was looking for to use in my projects.  
Thank you for creating it!

I encountered an issue while trying to run the Chromancer example, as demonstrated on https://zackees.github.io/fastled-wasm/. Unfortunately, it does not work out of the box for me.

I followed the instructions in the README and attempted to run it via the terminal. However, the build fails with an error stating that the `math_macros.h` header file cannot be found. 

Since this file exists in the FastLED repo, I also tried running it from the `examples/Chromancer` folder within the FastLED repo but encountered the same issue.

```
8.32 src/Chromancer.ino.cpp:21:10: fatal error: 'math_macros.h' file not found
8.32    21 | #include "math_macros.h"
8.32       |          ^~~~~~~~~~~~~~~
8.33 1 error generated.
8.34 *** [.pio/build/wasm/src/Chromancer.ino.o] Error 1
8.51 ========================== [FAILED] Took 8.50 seconds ==========================
```
Full log: [fastled-wasm-chromancer.log](https://github.com/user-attachments/files/17933242/fastled-wasm-chromancer.log)

**Comment by zackees** [comment]
Yeah I was doing some refactoring and had to move some files to the fl/ directory and the examples weren't under test.

I'm not sure if you are pulling the example from what you find in your arduino ide or whether you are using `fastled --init` to grab one of the examples. I recommend `fastled --init` because that version is under constant test and will be fresh.

Just run
`fastled.exe --init`

And then select chromancer and the example will be generated in the current directory.

Right now this fastled compiler is still in beta and is based on the bleeding edge rather than the release. So things will get more stable as we get closer to the final release.
