### ISSUE TITLE
Python's livereload module is installed, but not used.

### ISSUE THREAD

**Issue by hhrhhr** [zackees/fastled-wasm#5]
https://github.com/zackees/fastled-wasm/blob/4369225fbaa1b302577410c9514af6cde5e429f0/src/fastled/open_browser.py#L16-L21

Instead of _livereload_, _live-server_ is used, which is not installed by default. However, if you remove the comments in lines 16-20 and comment out line 21, then after compilation, livereload is launched, as expected.

It is possible that in Linux environment live-server is installed by default, but I am almost always in Windows environment (via MSYS2 or via using uv). I can install live-server (uv tool install live-server), but when starting the server I encounter "NotImplementedError":
```
  File "***\uv\tools\live-server\Lib\site-packages\tornado\tcpserver.py", line 157, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
                                    ^^^^^^^^^^^^^^^^^^^
  File "***\uv\tools\live-server\Lib\site-packages\tornado\netutil.py", line 268, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "***\uv\tools\live-server\Lib\site-packages\tornado\platform\asyncio.py", line 79, in add_handler
    self.asyncio_loop.add_reader(
  File "***\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\asyncio\events.py", line 534, in add_reader
    raise NotImplementedError
NotImplementedError
```

**Comment by zackees** [comment]
A live reloader server on python is nearly impossible to implement because of asyncio. I just wasted 5 hours trying to put it in myself. My entire computer is now borked for any python http server.

I should have just tried to do something silly like use flask. Instead I just put in npm inlined install into the package. It makes it way bigger but live-server is just performs so well that I'm just going to make this work and revisit this.

**Comment by hhrhhr** [comment]
`- from livereload import Server`
Oh, livereload worked quite well and took up 1% of the space that nodejs now takes up.
:cry: :crying_cat_face:

**Comment by zackees** [comment]
The problem is that livereload doesn't work on windows because of asyncio being busted. The app won't ever exit unless os_.exit(0) is used. Launching this in a multiprocess.Process doesn't work on windows either. Launching it as a subprocess means I can't control the headers to inject a header directing the browser not to use any cach. I lost an hour+ on trying to debug why I was getting the wrong sketch to appear when it turned out that the browswer wasn't honoring the no-cache directive in the meta tag.

To get the live reload feature to work without using live-server means I have to use flask/fastapi/starlet and invoke the live-reload in debug mode. Not exactly easy, but not the top most priority at this time. I'll revisit this later. Feel free to issue a PR if you are skilled enough to make this app use flask instead. The payload for that is tiny in comparison to embedding npm into the app.
